online-judge-tools/api-client

onlinejudge/service/aoj.py
tests/get_problem_aoj.py

port https://github.com/kmyk/online-judge-tools/pull/738 from kmyk/online-judge-tools

Support new URL of AOJ

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 10.0.2

---

CHANGELOG.md
onlinejudge/__about__.py

雑すぎないか？ もうちょっとまとめて release しましょう

RELEASE: 10.0.5

---

onlinejudge/service/google.py
tests/service_google.py

Mark @unittest.expectedFailure a test for the old GCJ problem

---

onlinejudge_api/main.py

fix https://github.com/online-judge-tools/api-client/issues/40

Replace ModuleNotFoundError with ImportError

---

onlinejudge/__init__.py

see https://github.com/online-judge-tools/oj/issues/771

Add a workaround for the new issue about installation

---

README.md
onlinejudge/service/codechef.py
tests/service_codechef.py

Remove CodeChef parser because it's now broken

---

.github/workflows/test.yml

Use the scheduled events of GitHub Actions

---

onlinejudge_api/login_service.py

Fix a bug of `oj-api login-service` on Zsh

---

onlinejudge/_implementation/utils.py
onlinejudge/service/codeforces.py
tests/get_problem_codeforces.py

Remove trailing spaces from sample cases of Codeforces

---

tests/get_problem_atcoder.py
tests/get_problem_library_checker.py
tests/get_problem_yukicoder.py
tests/service_atcoder.py
tests/utils.py

Import some tests from online-judge-tools/oj

---

README.md
onlinejudge/_implementation/language_guessing.py
onlinejudge_api/guess_language_id.py
onlinejudge_api/main.py
setup.cfg
tests/get_problem_yukicoder.py
tests/guess_language_id.py
tests/implementation_language_guessing.py
tests/utils.py

Add guess-language-id subcommand

---

onlinejudge/__init__.py

see https://github.com/online-judge-tools/verification-helper/issues/252

Update a workaround for conflicts of module

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 10.2.0

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 10.2.1

---

onlinejudge/service/yukicoder.py
tests/service_yukicoder.py

This pull request will be merged when other breaking changes happens.

Remove deprecated APIs about yukicoder

---

onlinejudge/service/google.py
tests/service_google.py

Fixes #46
Update parser part in onlinejudge/service/google.py. 
Also, I append a testcase for this issue.

Fix the bug that happens when GCJ has multiple samples (#46)

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 10.2.5

---

onlinejudge/service/yukicoder.py
tests/service_yukicoder.py

Add support of contests of yukicoder

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 10.3.2

---

onlinejudge/service/codeforces.py

fix https://github.com/online-judge-tools/api-client/issues/102
User-Agent で弾くならもっとまともな実装をしてくれという気持ちです

Hide User-Agent from Codeforces

---

README.md
onlinejudge/_implementation/utils.py
onlinejudge/service/__init__.py
onlinejudge/service/kagamiz.py
onlinejudge/utils.py
onlinejudge_api/main.py

- 提出機能のみ
- サンプル取得機能は省略
- テストは書いていません

Add Kagamiz Contest System

---

CONTRIBUTING.md
DESIGN.md

related https://github.com/online-judge-tools/.github/pull/4

Add DESIGN.md

---

onlinejudge/service/atcoder.py
tests/dispatch.py
tests/service_atcoder.py
tests/type.py

close #110 
壊れたけど直すの面倒なのでそのままにしておく

Remove broken code to get the detailed info from submissions on AtCoder

---

onlinejudge/_implementation/testcase_zipper.py
onlinejudge/_implementation/utils.py
onlinejudge/service/yukicoder.py
tests/get_problem_yukicoder.py
tests/service_yukicoder.py
tests/submit_code_yukicoder.py

~~破壊的変更をやめろという気持ち~~
いや、referer を付けてないのが悪かったぽいのでこちらの実装が悪い。ところでじゃあ CSRF token は何だったんだ？

Update for yukicoder

---

.github/workflows/test-unstable-workaround-macos.yml
.github/workflows/test-unstable-workaround-ubuntu.yml
.github/workflows/test-unstable-workaround-windows.yml
.github/workflows/test.yml
setup.py

It has already reached to its end-of-life.
See https://www.python.org/dev/peps/pep-0478/
cc @usk83 for #114

[breaking change] Finish Python 3.5 support

---

tests/service_atcoder.py

Fix failures at https://github.com/online-judge-tools/api-client/runs/1443795548

Update the test for an update of AtCoder

---

onlinejudge/_implementation/utils.py
onlinejudge/service/yukicoder.py
setup.cfg

This may fix https://github.com/online-judge-tools/api-client/issues/117

Add Referer for all requests via <form>

---

onlinejudge/_implementation/utils.py
onlinejudge/service/codeforces.py

close https://github.com/online-judge-tools/api-client/issues/117
こんどこそ直せたと思います

Use action in FormSender to fix the issue on Codeforces

---

onlinejudge/service/aoj.py

Selenium 経由でのログインだと cookie が取得できなくて動かないんだけど、将来のためにとりあえずできたところまで置いておく

Add AOJService.is_logged_in method

---

CHANGELOG.md
onlinejudge/__about__.py

https://github.com/online-judge-tools/api-client/issues/117 が直ってるといいなあ

RELEASE: 10.6.1

---

CHANGELOG.md
onlinejudge/__about__.py

RELEASE: 10.7.1

---

onlinejudge/service/csacademy.py
tests/get_problem_anarchygolf.py
tests/get_problem_csacademy.py
tests/get_problem_kattis.py
tests/get_problem_toph.py

close https://github.com/online-judge-tools/api-client/issues/37

Import tests about downloading sample cases from online-judge-tools/oj repository

---

onlinejudge/service/__init__.py
onlinejudge/service/atcoder_problems.py
onlinejudge_api/get_contest.py
tests/get_contest_atcoder_problems.py

Support AtCoder Problems

---

README.md

名前っぽいものが複数あるとどれを使っていいか困るのでよくない

Replace the title line of README.md with "online-judge-tools/api-client"

---

.github/workflows/format.yml
onlinejudge/_implementation/language_guessing.py
onlinejudge/service/atcoder.py
onlinejudge/service/codeforces.py
onlinejudge/service/csacademy.py
onlinejudge/service/facebook.py
onlinejudge/service/kagamiz.py
onlinejudge_api/main.py
setup.cfg
tests/service_yukicoder.py
tests/utils.py

Upgrade the formatters and linters

---

onlinejudge/dispatch.py

Supress logging from onlinejudge.dispatch module

---

README.md

"users" と "developers" の意味が曖昧だった

Update "Tips" section of README.md

---

onlinejudge/_implementation/utils.py
tests/get_problem_codeforces.py

隣接するタグ間に改行を挿入する

---

onlinejudge/_implementation/utils.py
tests/get_problem_codeforces.py

A clone of https://github.com/online-judge-tools/api-client/pull/155.

隣接する div タグ間に改行を挿入する / Insert newlines between adjacent div tags

---

setup.py

Migrate to importlib

---

onlinejudge_api/get_problem.py
tests/get_problem_atcoder.py

Fixes https://github.com/online-judge-tools/api-client/issues/149.

Fix the schema schema_compatibility
